import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ThemeContextProvider from "@/providers/theme-context";
import GaniSessionProvider from "@/providers/session";
import Header from "@/components/header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GaniSessionProvider>
        <ThemeContextProvider>
          <body
            className={`${geistMono.style} ${geistSans.style} w-screen h-screen antialiased flex flex-col bg-white dark:bg-[#090909] dark:text-gray-100`}
          >
            <Header />
            <main className="flex-grow overflow-y-auto">{children}</main>
          </body>
        </ThemeContextProvider>
      </GaniSessionProvider>
    </html>
  );
}
