import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ThemeContextProvider from "@/providers/theme-context";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import GaniSessionProvider from "@/providers/session";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <GaniSessionProvider>
          <ThemeContextProvider>{children}</ThemeContextProvider>
        </GaniSessionProvider>
      </body>
    </html>
  );
}
